set_property SRC_FILE_INFO {cfile:D:/Beni/Vhdl/ac/3.3-2017.4/3.3-2017.4.srcs/constrs_1/imports/Desktop/Zybo-Z7-Master.xdc rfile:../../../3.3-2017.4.srcs/constrs_1/imports/Desktop/Zybo-Z7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD LVCMOS33} [get_ports {swH[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {swH[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN W13 IOSTANDARD LVCMOS33} [get_ports {swH[2]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {swH[3]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVCMOS33} [get_ports {btnH[0]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {btnH[1]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVCMOS33} [get_ports {btnH[2]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {btnH[3]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {ic/rd2[0]} {ic/rd2[1]} {ic/rd2[2]} {ic/rd2[3]} {ic/rd2[4]} {ic/rd2[5]} {ic/rd2[6]} {ic/rd2[7]} {ic/rd2[8]} {ic/rd2[9]} {ic/rd2[10]} {ic/rd2[11]} {ic/rd2[12]} {ic/rd2[13]} {ic/rd2[14]} {ic/rd2[15]}]]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {ic/rd1[0]} {ic/rd1[1]} {ic/rd1[2]} {ic/rd1[3]} {ic/rd1[4]} {ic/rd1[5]} {ic/rd1[6]} {ic/rd1[7]} {ic/rd1[8]} {ic/rd1[9]} {ic/rd1[10]} {ic/rd1[11]} {ic/rd1[12]} {ic/rd1[13]} {ic/rd1[14]} {ic/rd1[15]}]]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {ic/insfet/pc[0]} {ic/insfet/pc[1]} {ic/insfet/pc[2]} {ic/insfet/pc[3]} {ic/insfet/pc[4]} {ic/insfet/pc[5]} {ic/insfet/pc[6]} {ic/insfet/pc[7]} {ic/insfet/pc[8]} {ic/insfet/pc[9]} {ic/insfet/pc[10]} {ic/insfet/pc[11]} {ic/insfet/pc[12]} {ic/insfet/pc[13]} {ic/insfet/pc[14]} {ic/insfet/pc[15]}]]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {ic/ic/reg/reg_file[2]_2[0]} {ic/ic/reg/reg_file[2]_2[1]} {ic/ic/reg/reg_file[2]_2[2]} {ic/ic/reg/reg_file[2]_2[3]} {ic/ic/reg/reg_file[2]_2[4]} {ic/ic/reg/reg_file[2]_2[5]} {ic/ic/reg/reg_file[2]_2[6]} {ic/ic/reg/reg_file[2]_2[7]} {ic/ic/reg/reg_file[2]_2[8]} {ic/ic/reg/reg_file[2]_2[9]} {ic/ic/reg/reg_file[2]_2[10]} {ic/ic/reg/reg_file[2]_2[11]} {ic/ic/reg/reg_file[2]_2[12]} {ic/ic/reg/reg_file[2]_2[13]} {ic/ic/reg/reg_file[2]_2[14]} {ic/ic/reg/reg_file[2]_2[15]}]]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {ic/ic/reg/reg_file[0]_0[0]} {ic/ic/reg/reg_file[0]_0[1]} {ic/ic/reg/reg_file[0]_0[2]} {ic/ic/reg/reg_file[0]_0[3]} {ic/ic/reg/reg_file[0]_0[4]} {ic/ic/reg/reg_file[0]_0[5]} {ic/ic/reg/reg_file[0]_0[6]} {ic/ic/reg/reg_file[0]_0[7]} {ic/ic/reg/reg_file[0]_0[8]} {ic/ic/reg/reg_file[0]_0[9]} {ic/ic/reg/reg_file[0]_0[10]} {ic/ic/reg/reg_file[0]_0[11]} {ic/ic/reg/reg_file[0]_0[12]} {ic/ic/reg/reg_file[0]_0[13]} {ic/ic/reg/reg_file[0]_0[14]} {ic/ic/reg/reg_file[0]_0[15]}]]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {ic/ic/reg/reg_file[1]_1[0]} {ic/ic/reg/reg_file[1]_1[1]} {ic/ic/reg/reg_file[1]_1[2]} {ic/ic/reg/reg_file[1]_1[3]} {ic/ic/reg/reg_file[1]_1[4]} {ic/ic/reg/reg_file[1]_1[5]} {ic/ic/reg/reg_file[1]_1[6]} {ic/ic/reg/reg_file[1]_1[7]} {ic/ic/reg/reg_file[1]_1[8]} {ic/ic/reg/reg_file[1]_1[9]} {ic/ic/reg/reg_file[1]_1[10]} {ic/ic/reg/reg_file[1]_1[11]} {ic/ic/reg/reg_file[1]_1[12]} {ic/ic/reg/reg_file[1]_1[13]} {ic/ic/reg/reg_file[1]_1[14]} {ic/ic/reg/reg_file[1]_1[15]}]]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {ic/ic/reg/reg_file[3]_3[0]} {ic/ic/reg/reg_file[3]_3[1]} {ic/ic/reg/reg_file[3]_3[2]} {ic/ic/reg/reg_file[3]_3[3]} {ic/ic/reg/reg_file[3]_3[4]} {ic/ic/reg/reg_file[3]_3[5]} {ic/ic/reg/reg_file[3]_3[6]} {ic/ic/reg/reg_file[3]_3[7]} {ic/ic/reg/reg_file[3]_3[8]} {ic/ic/reg/reg_file[3]_3[9]} {ic/ic/reg/reg_file[3]_3[10]} {ic/ic/reg/reg_file[3]_3[11]} {ic/ic/reg/reg_file[3]_3[12]} {ic/ic/reg/reg_file[3]_3[13]} {ic/ic/reg/reg_file[3]_3[14]} {ic/ic/reg/reg_file[3]_3[15]}]]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {ic/ic/reg/reg_file[4]_4[0]} {ic/ic/reg/reg_file[4]_4[1]} {ic/ic/reg/reg_file[4]_4[2]} {ic/ic/reg/reg_file[4]_4[3]} {ic/ic/reg/reg_file[4]_4[4]} {ic/ic/reg/reg_file[4]_4[5]} {ic/ic/reg/reg_file[4]_4[6]} {ic/ic/reg/reg_file[4]_4[7]} {ic/ic/reg/reg_file[4]_4[8]} {ic/ic/reg/reg_file[4]_4[9]} {ic/ic/reg/reg_file[4]_4[10]} {ic/ic/reg/reg_file[4]_4[11]} {ic/ic/reg/reg_file[4]_4[12]} {ic/ic/reg/reg_file[4]_4[13]} {ic/ic/reg/reg_file[4]_4[14]} {ic/ic/reg/reg_file[4]_4[15]}]]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {ic/ic/reg/reg_file[5]_5[0]} {ic/ic/reg/reg_file[5]_5[1]} {ic/ic/reg/reg_file[5]_5[2]} {ic/ic/reg/reg_file[5]_5[3]} {ic/ic/reg/reg_file[5]_5[4]} {ic/ic/reg/reg_file[5]_5[5]} {ic/ic/reg/reg_file[5]_5[6]} {ic/ic/reg/reg_file[5]_5[7]} {ic/ic/reg/reg_file[5]_5[8]} {ic/ic/reg/reg_file[5]_5[9]} {ic/ic/reg/reg_file[5]_5[10]} {ic/ic/reg/reg_file[5]_5[11]} {ic/ic/reg/reg_file[5]_5[12]} {ic/ic/reg/reg_file[5]_5[13]} {ic/ic/reg/reg_file[5]_5[14]} {ic/ic/reg/reg_file[5]_5[15]}]]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {ic/ic/reg/reg_file[7]_7[0]} {ic/ic/reg/reg_file[7]_7[1]} {ic/ic/reg/reg_file[7]_7[2]} {ic/ic/reg/reg_file[7]_7[3]} {ic/ic/reg/reg_file[7]_7[4]} {ic/ic/reg/reg_file[7]_7[5]} {ic/ic/reg/reg_file[7]_7[6]} {ic/ic/reg/reg_file[7]_7[7]} {ic/ic/reg/reg_file[7]_7[8]} {ic/ic/reg/reg_file[7]_7[9]} {ic/ic/reg/reg_file[7]_7[10]} {ic/ic/reg/reg_file[7]_7[11]} {ic/ic/reg/reg_file[7]_7[12]} {ic/ic/reg/reg_file[7]_7[13]} {ic/ic/reg/reg_file[7]_7[14]} {ic/ic/reg/reg_file[7]_7[15]}]]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 61 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {ic/ic/reg/reg_file[6]_6[0]} {ic/ic/reg/reg_file[6]_6[1]} {ic/ic/reg/reg_file[6]_6[2]} {ic/ic/reg/reg_file[6]_6[3]} {ic/ic/reg/reg_file[6]_6[4]} {ic/ic/reg/reg_file[6]_6[5]} {ic/ic/reg/reg_file[6]_6[6]} {ic/ic/reg/reg_file[6]_6[7]} {ic/ic/reg/reg_file[6]_6[8]} {ic/ic/reg/reg_file[6]_6[9]} {ic/ic/reg/reg_file[6]_6[10]} {ic/ic/reg/reg_file[6]_6[11]} {ic/ic/reg/reg_file[6]_6[12]} {ic/ic/reg/reg_file[6]_6[13]} {ic/ic/reg/reg_file[6]_6[14]} {ic/ic/reg/reg_file[6]_6[15]} ic/mpgDebouncedButton {ic/alu/branchAddressS[0]} {ic/alu/branchAddressS[1]} {ic/alu/branchAddressS[2]} {ic/alu/branchAddressS[3]} {ic/alu/branchAddressS[4]} {ic/alu/branchAddressS[5]} {ic/alu/branchAddressS[6]} {ic/alu/branchAddressS[7]} {ic/alu/branchAddressS[8]} {ic/alu/branchAddressS[9]} {ic/alu/branchAddressS[10]} {ic/alu/branchAddressS[11]} {ic/alu/branchAddressS[12]} {ic/alu/branchAddressS[13]} {ic/alu/branchAddressS[14]} {ic/alu/branchAddressS[15]} ic/alu/zero {ic/alu/extImm[0]} {ic/alu/extImm[1]} {ic/alu/extImm[2]} {ic/alu/extImm[3]} {ic/alu/extImm[4]} {ic/alu/extImm[5]} {ic/alu/extImm[6]} {ic/alu/extImm[7]} {ic/alu/nextInstruction[0]} {ic/alu/nextInstruction[1]} {ic/alu/nextInstruction[2]} {ic/alu/nextInstruction[3]} {ic/alu/nextInstruction[4]} {ic/alu/nextInstruction[5]} {ic/alu/nextInstruction[6]} {ic/alu/nextInstruction[7]} {ic/alu/nextInstruction[8]} {ic/alu/nextInstruction[9]} {ic/alu/nextInstruction[10]} {ic/alu/nextInstruction[11]} {ic/alu/nextInstruction[12]} {ic/alu/nextInstruction[13]} {ic/alu/nextInstruction[14]} {ic/alu/nextInstruction[15]} {ic/insfet/branchAddress[0]} ic/insfet/pCSrcControl ic/branch]]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
